//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuterra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nuterra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;bacon.blend&apos;
        ///# www.blender.org
        ///mtllib bacon.mtl
        ///o Bacon_Cube
        ///v 3.472792 -0.415830 -0.176392
        ///v -0.540784 -0.391782 -0.176392
        ///v 3.539587 0.396662 -0.176391
        ///v -0.459573 0.462572 -0.176392
        ///v -0.523766 -0.205118 -0.176641
        ///v -0.520435 0.091477 -0.176643
        ///v -0.514449 0.174250 -0.176643
        ///v -0.492534 0.281272 -0.176641
        ///v 3.516438 -0.221289 -0.176641
        ///v 3.523625 0.083188 -0.176643
        ///v 3.531012 0.154310 -0.176643
        ///v 3.527974 0.265728 -0.176640
        ///v -0.382967 -0.194578 -0.17929 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bacon {
            get {
                return ResourceManager.GetString("bacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bacon_icon_png {
            get {
                object obj = ResourceManager.GetObject("bacon_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bacon_material_png {
            get {
                object obj = ResourceManager.GetObject("bacon_material_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib GSOMGunFixed_111.1.mtl
        ///o GSOFixedMachineGunGun111.001
        ///v -0.072558 0.144507 -0.022805
        ///v -0.072558 -0.123363 -0.022805
        ///v -0.051306 -0.123363 0.021171
        ///v -0.051306 0.144507 0.021171
        ///v 0.000000 -0.123363 0.039387
        ///v 0.000000 0.144507 0.039387
        ///v 0.051306 -0.123363 0.021171
        ///v 0.051306 0.144507 0.021171
        ///v 0.072558 -0.123363 -0.022805
        ///v 0.072558 0.144507 -0.022805
        ///v 0.051306 -0.123363 -0.066782
        ///v 0.051306 0.144507 -0.066782
        ///v -0.051306 0.14 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string banana_barrel {
            get {
                return ResourceManager.GetString("banana_barrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib GSOMGunFixed_111.3.mtl
        ///o GSOFixedMachineGun111
        ///v -0.066343 -0.169880 -0.394998
        ///v 0.066343 -0.169880 -0.394998
        ///v 0.066343 0.169880 -0.394998
        ///v -0.066343 0.169880 -0.394998
        ///v -0.227408 0.216331 -0.394998
        ///v -0.227408 -0.216330 -0.394998
        ///v -0.089136 -0.192673 -0.394998
        ///v -0.216331 -0.227408 -0.394998
        ///v -0.100214 -0.227408 -0.394998
        ///v -0.089136 -0.216330 -0.394998
        ///v -0.089136 0.192673 -0.394998
        ///v -0.216331 0.227408 -0.394998
        ///v -0.10021 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string banana_base {
            get {
                return ResourceManager.GetString("banana_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] banana_blast_material_png {
            get {
                object obj = ResourceManager.GetObject("banana_blast_material_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///#
        ///#
        ///
        ///mtllib banana_body.mtl
        ///
        ///
        ///#
        ///#  Mesh
        ///#
        ///g  Mesh
        ///
        ///
        ///#
        ///#  Mesh_Material_NONE
        ///#
        ///usemtl  Mesh_Material_NONE
        ///
        ///v 0.028839 0.442283 -0.174157
        ///v 0.024566 0.432397 -0.204753
        ///v 0.032097 0.474267 -0.270359
        ///v 0.034296 0.495044 -0.253825
        ///v 0.000000 0.502702 -0.265062
        ///v 0.000000 0.514848 -0.233508
        ///v 0.032097 0.510397 -0.229681
        ///v 0.096872 0.320758 -0.055683
        ///v 0.083088 0.322977 -0.140451
        ///v -0.034297 0.495044 -0.253825
        ///v -0.032098 0.474267 -0.270359
        ///v -0.024567 0.432397 -0.204753
        ///v -0.028840 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string banana_body {
            get {
                return ResourceManager.GetString("banana_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] banana_gloss_material_png {
            get {
                object obj = ResourceManager.GetObject("banana_gloss_material_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] banana_icon_png {
            get {
                object obj = ResourceManager.GetObject("banana_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] banana_material_png {
            get {
                object obj = ResourceManager.GetObject("banana_material_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib cockpit_large.mtl
        ///o Plane.054_Plane.001_Plane.054_Plane.005
        ///v -0.000713 -0.637915 0.999799
        ///v 0.144842 -0.497578 1.145066
        ///v -0.145930 -0.497577 1.145404
        ///v -0.146268 -0.497472 0.854633
        ///v 0.144504 -0.497472 0.854295
        ///vt 0.283915 0.886225
        ///vt 0.319632 0.921945
        ///vt 0.248194 0.921943
        ///vt 0.248197 0.850505
        ///vt 0.319635 0.850507
        ///vn 0.0008 -0.7196 0.6944
        ///vn -0.6946 -0.7194 0.0005
        ///vn -0.0008 -0.7191 -0.6949
        ///vn 0.6946 -0.7194 -0.0011
        ///usemtl Material.015
        ///s off
        ///f  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cockpit_large {
            get {
                return ResourceManager.GetString("cockpit_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cockpit_large_icon_png {
            get {
                object obj = ResourceManager.GetObject("cockpit_large_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib cockpit_small.mtl
        ///o Sphere.001
        ///v 0.070349 0.067098 -0.353667
        ///v 0.137994 0.067098 -0.333147
        ///v 0.151707 0.056513 -0.366252
        ///v 0.077339 0.056513 -0.388811
        ///v 0.316490 0.067098 0.151793
        ///v 0.299825 0.067098 0.200337
        ///v 0.329618 0.056513 0.220244
        ///v 0.366252 0.056513 0.151707
        ///v -0.254980 0.067098 -0.254980
        ///v -0.200336 0.067098 -0.299825
        ///v -0.220244 0.056513 -0.329618
        ///v -0.280317 0.056513 -0.280317
        ///v -0.200337 0.067098 0.299825
        ///v -0.254980 0.067098 0.254980 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cockpit_small {
            get {
                return ResourceManager.GetString("cockpit_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib cockpit_small_2.mtl
        ///o Cube.008_Cube.000
        ///v 0.000142 -0.428339 -0.364314
        ///v -0.257508 -0.428339 -0.257709
        ///v -0.000000 -0.318645 -0.000000
        ///v 0.257710 -0.428339 -0.257508
        ///v 0.364314 -0.493816 0.000142
        ///v -0.000143 -0.431387 0.364314
        ///v -0.257709 -0.431387 0.257508
        ///v 0.257508 -0.431387 0.257710
        ///v -0.364314 -0.493816 -0.000143
        ///vt 0.172120 0.649550
        ///vt 0.153470 0.630900
        ///vt 0.185307 0.617713
        ///vt 0.198494 0.649550
        ///vt 0.217144 0.630900
        ///vt 0.198494 0.585876
        ///vt 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cockpit_small_2 {
            get {
                return ResourceManager.GetString("cockpit_small_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cockpit_small_2_icon_png {
            get {
                object obj = ResourceManager.GetObject("cockpit_small_2_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cockpit_small_icon_png {
            get {
                object obj = ResourceManager.GetObject("cockpit_small_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Name&quot;: &quot;Magical Block&quot;,
        ///	&quot;Description&quot;: &quot;A very nice block, loaded from the file system\nThis one is magical!&quot;, //You can make multiple lines with \n
        ///	&quot;ID&quot;: 534968, //A random ID that must be unique		
        ///	&quot;IDNetHex&quot;: &quot;4ff30da9fd33fff4&quot;, //Get a random hex from https://www.random.org/bytes/ (8 bytes work)
        ///
        ///	&quot;Faction&quot;: 1, //GSO = 1|0, GeoCorp = 2, EXP = 3, Venture = 4, HawkEye = 5, Special = 6
        ///	&quot;Category&quot;: 0, //Control = 1, Standard = 2|0, Wheels = 3, Weapons = 4, Accessories = 5, Power = 6, Base = 7, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleJson {
            get {
                return ResourceManager.GetString("ExampleJson", resourceCulture);
            }
        }
    }
}
